export const BIBLE_QUESTIONS = [
    // 簡單
    { id: 1, category: "猜人物", difficulty: "簡單", question: "帶領以色列人出埃及，並在西奈山領受十誡的領袖是誰？", answer: "摩西" },
    { id: 2, category: "聖經填空", difficulty: "簡單", question: "「起初，神創造______。」(創世記1:1)", answer: "天地" },
    { id: 8, category: "聖經填空", difficulty: "簡單", question: "「耶和華是我的______，我必不致缺乏。」(詩篇23:1)", answer: "牧者" },
    { id: 9, category: "聖經歷史", difficulty: "簡單", question: "耶穌降生在哪個城市？", answer: "伯利恆" },
    { id: 15, category: "猜人物", difficulty: "簡單", question: "耶穌在地上的養父（馬利亞的丈夫）叫什麼名字？", answer: "約瑟" },
    { id: 19, category: "聖經填空", difficulty: "簡單", question: "「常常喜樂，不住地______，凡事謝恩...」(帖前5:16)", answer: "禱告" },
    
    // 中等
    { id: 3, category: "聖經歷史", difficulty: "中等", question: "以色列的第一位國王是誰？", answer: "掃羅" },
    { id: 4, category: "猜人物", difficulty: "中等", question: "耶穌的十二門徒中，為了三十塊錢出賣耶穌的是誰？", answer: "加略人猶大" },
    { id: 5, category: "聖經填空", difficulty: "中等", question: "「神愛世人，甚至將他的______賜給他們...」(約翰福音3:16)", answer: "獨生子" },
    { id: 10, category: "猜人物", difficulty: "中等", question: "因為逃避神的呼召，而在大魚的肚子裡待了三天三夜的先知是誰？", answer: "約拿" },
    { id: 12, category: "猜人物", difficulty: "中等", question: "誰只用了一塊石頭和機弦，就擊敗了非利士的巨人歌利亞？", answer: "大衛" },
    { id: 13, category: "聖經填空", difficulty: "中等", question: "「愛是恆久忍耐，又有______...」(哥林多前書13:4)", answer: "恩慈" },
    { id: 17, category: "聖經歷史", difficulty: "中等", question: "摩西死後，是誰接續他帶領以色列人過約旦河進入迦南地？", answer: "約書亞" },
    { id: 21, category: "猜人物", difficulty: "中等", question: "他在墳墓裡已經四天了，後來耶穌流淚並大聲呼叫使他從死裡復活。他是誰？", answer: "拉撒路" },
    { id: 22, category: "聖經填空", difficulty: "中等", question: "「你們要先求他的______和他的______，這些東西都要加給你們了。」(太6:33)", answer: "國、義" },
    { id: 25, category: "聖經歷史", difficulty: "中等", question: "耶穌被釘十字架的地方，名叫「各各他」，翻出來是什麼意思？", answer: "髑髏地" },
    { id: 37, category: "猜人物", difficulty: "中等", question: "賣了長子名分給弟弟雅各的人是誰？", answer: "以掃" },
    { id: 46, category: "猜人物", difficulty: "中等", question: "誰在五旬節聖靈降臨後，站起來講道，一天之內有三千人信主洗禮？", answer: "彼得" },
  
    // 困難
    { id: 6, category: "聖經歷史", difficulty: "困難", question: "尼希米帶領以色列人回歸耶路撒冷，主要是為了重建什麼？", answer: "城牆" },
    { id: 7, category: "猜人物", difficulty: "困難", question: "原本名叫亞伯蘭，後來被神改名，並被稱為「信心之父」的是誰？", answer: "亞伯拉罕" },
    { id: 11, category: "聖經填空", difficulty: "困難", question: "「我就是______、______、______；若不藉著我，沒有人能到父那裡去。」(約14:6)", answer: "道路、真理、生命" },
    { id: 14, category: "聖經歷史", difficulty: "困難", question: "哪一個帝國摧毀了所羅門建立的第一聖殿，並將猶大人擄去？", answer: "巴比倫" },
    { id: 16, category: "聖經填空", difficulty: "困難", question: "聖靈所結的果子：仁愛、喜樂、和平、忍耐、恩慈、良善、______、______、______。(加5:22)", answer: "信實、溫柔、節制" },
    { id: 18, category: "猜人物", difficulty: "困難", question: "誰是舊約中最後一位先知，穿著駱駝毛的衣服，並且為耶穌施洗？", answer: "施洗約翰" },
    { id: 20, category: "聖經歷史", difficulty: "困難", question: "使徒保羅在哪個城市看見了寫著「未識之神」的祭壇？", answer: "雅典" },
    { id: 23, category: "聖經歷史", difficulty: "困難", question: "雅各在雅博渡口與神（天使）摔跤後，他的名字被神改為什麼？", answer: "以色列" },
    { id: 24, category: "猜人物", difficulty: "困難", question: "聖經中記載壽命最長的人是誰？他活了969歲。", answer: "瑪土撒拉" },
    { id: 26, category: "聖經歷史", difficulty: "困難", question: "以色列分裂後，北國的第一任國王是誰？", answer: "耶羅波安" },
    { id: 27, category: "猜人物", difficulty: "困難", question: "誰是帶領以色列人回歸並教導律法的文士？", answer: "以斯拉" },
    { id: 28, category: "聖經填空", difficulty: "困難", question: "「信就是所望之事的實底，是______的確據。」(希伯來書11:1)", answer: "未見之事" },
    { id: 29, category: "猜人物", difficulty: "困難", question: "聖經中第一位為主殉道的門徒是誰？", answer: "司提反" },
    { id: 30, category: "猜人物", difficulty: "困難", question: "耶穌被捕時，誰拔刀削掉大祭司僕人的右耳？", answer: "彼得" },
    { id: 31, category: "聖經填空", difficulty: "困難", question: "「我們曉得萬事都互相效力，叫______的人得益處...」(羅馬書8:28)", answer: "愛神" },
    { id: 32, category: "猜人物", difficulty: "困難", question: "誰與保羅一起在腓立比的監獄裡半夜唱詩讚美神，引發大地震？", answer: "西拉" },
    { id: 33, category: "聖經歷史", difficulty: "困難", question: "保羅在哪個島上被毒蛇咬卻沒有受傷？", answer: "米利大島(馬耳他島)" },
    { id: 34, category: "猜人物", difficulty: "困難", question: "舊約中，唯一一位成為以色列士師的女性是誰？", answer: "底波拉" },
    { id: 35, category: "聖經填空", difficulty: "困難", question: "「因為世人都犯了罪，虧缺了神的______。」(羅馬書3:23)", answer: "榮耀" },
    { id: 36, category: "聖經歷史", difficulty: "困難", question: "啟示錄是使徒約翰被放逐到哪個島上時所寫的？", answer: "拔摩海島" },
    { id: 38, category: "聖經填空", difficulty: "困難", question: "「你要專心仰賴耶和華，不可倚靠自己的______。」(箴言3:5)", answer: "聰明" },
    { id: 39, category: "聖經歷史", difficulty: "困難", question: "摩西派了十二個探子去窺探迦南地，其中只有哪兩個人回報好消息？", answer: "約書亞和迦勒" },
    { id: 40, category: "猜人物", difficulty: "困難", question: "誰在路上遇見耶穌後，決定把所有財產的一半給窮人，並訛詐了誰就還他四倍？", answer: "撒該" },
    { id: 41, category: "聖經填空", difficulty: "困難", question: "「世人哪，耶和華已指示你何為善...只要你行公義，______，存謙卑的心，與神同行。」(彌6:8)", answer: "好憐憫" },
    { id: 42, category: "聖經歷史", difficulty: "困難", question: "在舊約中，哪一座城市因為罪惡極大，被神從天上降下硫磺與火毀滅？", answer: "所多瑪(和蛾摩拉)" },
    { id: 43, category: "猜人物", difficulty: "困難", question: "誰為了保護猶太人不被滅族，冒死違例去見波斯國王，並說「我若死就死吧」？", answer: "以斯帖" },
    { id: 44, category: "聖經填空", difficulty: "困難", question: "「我已經與基督同釘十字架，現在活著的不再是我，乃是______在我裡面活著。」(加2:20)", answer: "基督" },
    { id: 45, category: "聖經歷史", difficulty: "困難", question: "哪一個帝國摧毀了北國以色列，並將人民擄走？", answer: "亞述帝國" },
    { id: 47, category: "聖經填空", difficulty: "困難", question: "「你要保守你心，勝過保守一切，因為一生的______是由心發出。」(箴言4:23)", answer: "果效" },
    { id: 48, category: "聖經歷史", difficulty: "困難", question: "亞伯拉罕獻以撒的地方在哪座山上？", answer: "摩利亞山" },
    { id: 49, category: "猜人物", difficulty: "困難", question: "新約中，誰被稱為「安慰之子」，並且賣了田地把錢放在使徒腳前？", answer: "巴拿巴" },
    { id: 50, category: "聖經填空", difficulty: "困難", question: "「草必枯乾，花必凋殘，惟有我們神的話必______。」(以賽亞書40:8)", answer: "永遠立定" }
  ];